### ISSUE TITLE
S15 (Change Ace Value) | 1 pt

### ISSUE THREAD

**Issue by cmplowman** [jennaborowy/square-fall24-blackjack#16]
User Story 15: Change Ace Value (Medium)

**Comment by cmplowman** [comment]
Fixed with commit f4cb66733bf9fd030123915c7f6b9edec2ee8cd1

**Comment by cmplowman** [comment]
Passed testing with commit cba4578e18bc354bd87735576774f6ad659dcede

**Comment by ccwalk** [comment]
edited scenarios to prompt for ace 7b2abd86e6a854476c8cf1501c60039eb12bf06f

**Comment by ccwalk** [comment]
added testing for double pocket ace scenarios 83cd3c0748875435b1d27e8df1eda876868a2a2f
