### ISSUE TITLE
S3 (Create Account) | 2 pt

### ISSUE THREAD

**Issue by cmplowman** [jennaborowy/square-fall24-blackjack#4]
User Story 3: Create Account

**Comment by emma-h1** [comment]
109a9b8d54b81d07d27829db7566e11f86f5c25c

**Comment by jennaborowy** [comment]
895a2f8687a148884abec4d34aa36af938b3e383

**Comment by jennaborowy** [comment]
ad9e0a3eb801f7bd5a5e4f74200248ccea696c30

**Comment by jennaborowy** [comment]
5aff23dd75c51ee35bf0c5c2927b7446371f067a

**Comment by jennaborowy** [comment]
7ed45ab19079a1d6e0f778986cd3eea8288c5065
